### ISSUE TITLE
Profile dotfile includes multiple blocks of things only defined once

### ISSUE THREAD

**Issue by danclegg** [byu-oit/av-scheduling-panel-deployment#10]
In the setup scripts of the system, .profile is appended with the following once, but in a running system it appears many times.

> #golang
> export GOPATH=/home/pi/go
> export GOSRC=/home/pi/go/src
> export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:~/go/bin

**Comment by cjreeder** [comment]
.profile was being updated by the scheduling-panel.sh script that the scheduling-panel.service was calling.   This was causing all of these entries to constantly show up after each restart of the service and overrunning the .profile file with repeat entries.   This bug has been fixed. :)
